### ISSUE TITLE
Add support for multiline messages

### ISSUE THREAD

**Issue by Bibliofile** [Bibliofile/bh-logReader#1]
Currently, if a message contains multiple lines, each line is shown as a different message. This should be fixed so messages are correctly parsed even if they contain multiple lines

**Comment by ghost** [comment]
A lot of code needs to be changed for this, so it's best to do this first.

**Comment by Bibliofile** [comment]
Agreed, I am guessing that this needs to be done by splitting by... date? 

```
var lines = this.result.split("\n");
```

will be changed to something along the lines of 

```
var lines = this.result.split(/\d\d\d\d-\d\d-\d\d/);
```

I'm new to regex syntax. Not even sure if this is the right way to go.

**Comment by ghost** [comment]
The latest commit fixes this issue.
