### ISSUE TITLE
Lower case username in chat messages

### ISSUE THREAD

**Issue by ghost** [Bibliofile/bh-logReader#3]
@Bibliofile in some of your example logs, your username is in lower case letters.
Is this manually edited or is it possible that a username can be lowercased?
Currently the script only recognizes chat messages with the username all upper case letters.

**Comment by Bibliofile** [comment]
A username can be forced lowercase by manually editing the join name -- a normal player will never be able to do this as Dave converts each name to uppercase before saving it. We likely should manually convert each chat message name to uppercase. (This, at least, is something I can handle :smile:)
